FROM node:11

MAINTAINER Henkka T


RUN apt-get update

# Installing the packages needed to run Nightmare
RUN apt-get install -y \
  xvfb \
  x11-xkb-utils \
  xfonts-100dpi \
  xfonts-75dpi \
  xfonts-scalable \
  xfonts-cyrillic \
  x11-apps \
  clang \
  libdbus-1-dev \
  libgtk2.0-dev \
  libnotify-dev \
  libgnome-keyring-dev \
  libgconf2-dev \
  libasound2-dev \
  libcap-dev \
  libcups2-dev \
  libxtst-dev \
  libxss1 \
  libnss3-dev \
  gcc-multilib \
  g++-multilib

ENV DEBUG="nightmare"
ENV NODE_ENV=production
ENV PORT=1234

COPY . /var/www
WORKDIR /var/www

RUN npm install -g yarn
RUN npm install
RUN yarn install


EXPOSE $PORT


ENTRYPOINT ["npm","start"]

CMD ['npm start']